name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-vendor
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Install front dependencies
        run: npm ci

      - name: Install back dependencies
        uses: php-actions/composer@v1

      - name: Test ESLint
        run: npm run test:eslint

      - name: Test Stylelint
        run: npm run test:stylelint

      - name: Test Typescript
        run: npm run test:type-check

      - name: Test Markdown
        run: npm run test:markdown

      - name: Test Jest
        run: npm run test

      - name: Build
        run: npm run build
